### ISSUE TITLE
How to fully uninstall pretty_errors in all conda env?

### ISSUE THREAD

**Issue by pengzhiliang** [onelivesleft/PrettyErrors#17]
Hi~, When I installed pretty_errors via pip, I inadvertently chose let it act on all my envs. Therefore, how can I fully uninstall it or do something to fix it? Thank u~

**Comment by onelivesleft** [comment]
Install it again, then run `python -m pretty_errors` : there should be an option `C` to clean up any startup files.  After you clean them, you can uninstall pretty errors.

**Comment by pengzhiliang** [comment]
Thank you very much!!!  And when I debug in pycharm, I can easily locate error via clicking the link before installing pretty_errors. After installing it, this function disappeared. So how can i do to fix it? Thank u!

**Comment by onelivesleft** [comment]
If you edit the file you are importing pretty_errors in (running the command above should list it) you can add a call to `pretty_errors.configure()`  to change the settings.   

Using `pretty_errors.configure(display_link=True)`  will output text which looks like the line default python outputs; this is clickable in vscode, so hopefully pycharm will also be able to use it.

Please see the docs when you scroll down at https://github.com/onelivesleft/PrettyErrors  to see other ways you can personalise pretty_errors.

**Comment by pengzhiliang** [comment]
@onelivesleft Ok, Thank you very mush.
