### ISSUE TITLE
Only last Exception shown

### ISSUE THREAD

**Issue by pmatias** [onelivesleft/PrettyErrors#19]
While dealing with multiple exceptions ("During handling of the above exception, another exception occurred: ..."), Pretty Errors will show only the last one. 

Is there a way to show all of them?

**Comment by onelivesleft** [comment]
This could be a bug in pretty errors; this is the message that will display if pretty errors raises an exception while handling an exception. Or it could be something else.  Can you post a screenshot of it happening?  What does it look like when the same error happens and you are not using pretty errors?

**Comment by onelivesleft** [comment]
Is there any way you could make a small script which reproduces this scenario, which I could use to work against? 

It's not currently built to take this situation into account, but in the meantime you could try `pretty_errors.replace_stderr()`; it should give you output containing both traces, though I'm not sure how well it will be formatted.

**Comment by pmatias** [comment]
Thanks, I'll try your workaround, in the meantime, this should generate a double exception:

```
try:
    myval = [1,2]
    print(myval[3])
except:
    print("First exception")
    raise OSError
```

**Comment by onelivesleft** [comment]
This should now be handled correctly if you update to v1.2.16.  See config options `inner_exception_message` and `inner_exception_separator` in the readme if you want to config it.

**Comment by pmatias** [comment]
This is great @onelivesleft, thanks for the amazingly quick response on this!

I'll be trying it out in a few minutes.

**Comment by pmatias** [comment]
I've just tried it in my project, and indeed works as expected!

Thanks again for taking care of this!

**Comment by onelivesleft** [comment]
👍

**Comment by saulzar** [comment]
This also seems to break when you explicitly don't want to show the inner exception - which you can control in python normally by rethrowing an error like this:

```
def my_function():
   raise ValueError("big problems!")

try:
   my_function():
catch ValueError as e:
  raise e from None

```

The stack trace should hide the inner exception (i.e. there should be no mention of `my_function` in the stack trace)

**Comment by onelivesleft** [comment]
I'm not following you, normal python shows it too:
```python
▶ python regular.py
Traceback (most recent call last):
  File "regular.py", line 8, in <module>
    raise e from None
  File "regular.py", line 6, in <module>
    my_function()
  File "regular.py", line 3, in my_function
    raise ValueError("big problems!")
ValueError: big problems!

▶ python pretty.py

pretty.py 9 <module>
raise e from None

pretty.py 7 <module>
my_function()

pretty.py 4 my_function
raise ValueError("big problems!")
ValueError
:
big problems!
```

**Comment by saulzar** [comment]
Hi ! Sorry my example was not a good one, I realise that to have the desired behaviour it is necessary to throw a new exception and not just re-throw the old one.

To see the difference in normal python remove the "from None" which then matches the output from pretty_errors.


```
def my_function():
   raise ValueError("big problems!")

try:
   my_function()
except ValueError as e:
  raise ValueError("test") from None

```

python regular.py
```
Traceback (most recent call last):
  File "regular.py", line 9, in <module>
    raise ValueError("test") from None
ValueError: test
```


with pretty_errors:

```
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
regular.py 7 <module>
my_function()

regular.py 4 my_function
raise ValueError("big problems!")

ValueError:
big problems!

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
regular.py 9 <module>
raise ValueError("test") from None

ValueError:
test

```

**Comment by saulzar** [comment]
The behaviour is described in https://docs.python.org/3/library/exceptions.html - it sets a flag __cause__  (and __suppress_context__) on the exception which makes it hide the inner exception.

**Comment by onelivesleft** [comment]
Thanks for the link, updated to v1.2.17.
