### ISSUE TITLE
pretty_errors not working without explicit import.

### ISSUE THREAD

**Issue by nisarg-ujjainkar** [onelivesleft/PrettyErrors#20]
Hi, 
I ran `sudo python -m pretty_errors` and tried installing both sitecustomize.py and pretty_errors.pth (not at the same time) but, pretty_errors does not seem to work.

When installing either of the files, I installed them at /usr/local/lib/python3.8/dist-packages.

With "sitecustomize.py"  it simply does not have any effect.
With "pretty_errors.pth" it shows error

```
Error processing line 2 of /usr/local/lib/python3.8/dist-packages/pretty_errors.pth:

  Traceback (most recent call last):
    File "/usr/lib/python3.8/site.py", line 175, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "/usr/local/lib/python3.8/dist-packages/pretty_errors/__init__.py", line 1, in <module>
      import sys, re, colorama, os, time, linecache
  ModuleNotFoundError: No module named 'colorama'
```

Even though, Colorama is installed and I the latest version. How do I solve this issue?

**Comment by nisarg-ujjainkar** [comment]
Edit: the error has gone and now using "pretty_errors.pth" also has no effect.

**Comment by onelivesleft** [comment]
Make sure you run pip the same way you run python, to make sure you are working with the same python install.  i.e. don't do `sudo pip install...`, do `sudo python -m pip install...`

**Comment by nisarg-ujjainkar** [comment]
It is working now. Had to uninstall pretty_errors and then had to install it without `sudo`, then configure without `sudo`.
Now the only folder I can install the config file to, is `/home/nisarg/.local/lib/python3.8/site-packages`.
Using `sudo` seems to be the problem.
