### ISSUE TITLE
Colors in sublime text

### ISSUE THREAD

**Issue by krillin666** [onelivesleft/PrettyErrors#24]
Hello,

The colours in the error output do not appear in sublime text 3, while if I run the same code in the terminal they do appear.

Output error example in sublime text:
![Screenshot from 2020-11-15 15-27-59](https://user-images.githubusercontent.com/60305303/99189084-582e4f00-2757-11eb-8d2f-c9990dc15700.png)

Thank you !

**Comment by onelivesleft** [comment]
Sublime doesn't output color, at least not by default.  Apparently this guy got it to work: https://forum.sublimetext.com/t/build-with-colored-output/46465
