### ISSUE TITLE
Missing import time  in usercustomize.py

### ISSUE THREAD

**Issue by dchen327** [onelivesleft/PrettyErrors#25]
When trying to change configs globally by uncommenting the `pretty_errors.configure(` in `usercustomize.py`, an error is thrown since `time` is not imported, but is used in `timestamp_function = time.perf_counter`.

On my end, I've just added `import time` to the top of the file; however, when generating the file `import time` should be added as well.

**Comment by onelivesleft** [comment]
I'm not sure whether `import time` should be added, or whether a comment should be added to the line instead.  Will think on it then do one of the two.  Thank you!

**Comment by alecgirman** [comment]
The error happens because of `timestamp_function = time.perf_counter` (on line 61), so an `import time` added to usercustomize.py should fix it.  I made a pull request that addresses the issue.

**Comment by vamsis-adapa** [comment]
Perhaps instead of importing the whole time library, import just perf_counter function, and modify  "line 61, pretty_errors/__main__.py" to `timestamp_function = perf_counter`
