### ISSUE TITLE
Related projects

### ISSUE THREAD

**Issue by alexmojaki** [onelivesleft/PrettyErrors#3]
Just letting you know about some work in this space:

https://github.com/Qix-/better-exceptions
https://github.com/cknd/stackprinter
https://github.com/skorokithakis/tbvaccine
https://github.com/aroberge/friendly-traceback

https://docs.python.org/3.8/library/cgitb.html

I'm currently working on improving the tracebacks in IPython [here](https://github.com/ipython/ipython/pull/11886) with a new generic library I've made for tracebacks. I also have a PR to integrate it into stackprinter.

**Comment by ankostis** [comment]
It would be good if you included the above list in the README for fellow programmers.

**Comment by alexmojaki** [comment]
More:

https://github.com/HallerPatrick/frosch
https://github.com/willmcgugan/rich

Also my library [stack_data](https://github.com/alexmojaki/stack_data) is now complete and integrated into IPython in master. A few things it can offer that you may struggle with otherwise:

- Highlighting the exact executing node, e.g. as in https://github.com/ipython/ipython/pull/12150
- Showing multiline statements in full without having to add superfluous lines of context otherwise
- Handling repeated frames, e.g. in recursion errors

**Comment by alexmojaki** [comment]
Also

- https://github.com/mbarkhau/pretty-traceback, which has its own list at the bottom including new ones:
- https://github.com/chillaranand/ptb
- https://github.com/staticshock/colored-traceback.py
- https://github.com/laurb9/rich-traceback
- https://github.com/nir0s/backtrace
