### ISSUE TITLE
Can I prettify `traceback.print_exc()` using this module?

### ISSUE THREAD

**Issue by bombs-kim** [onelivesleft/PrettyErrors#31]
I played with this module a bit and I found that the output of `traceback.print_exc()` is not changed by importing `pretty_errors`. Is there a way I can prettify this also? Thanks in advance!

**Comment by onelivesleft** [comment]
Instead of `traceback.print_exc()` use `traceback.format_exc()`, and feed it to `pretty_errors.StdErr().write`.  You'll need to append an extra `\n` onto it to make it trigger the output correctly.  For example:

```python
err_out = pretty_errors.StdErr()
def output_error(s):
    err_out.write(s + "\n")

...

try:
    raise KeyError
except:
    output_error(traceback.format_exc())
```
