### ISSUE TITLE
Django Compatibility?

### ISSUE THREAD

**Issue by silentjay** [onelivesleft/PrettyErrors#33]
Has anyone got this lib working with Django, esp when using a virtualenv? I haven't had any luck yet and I don't really know where to start.

**Comment by onelivesleft** [comment]
I have no Django experience, you'd be better asking about this on a Django forum.

**Comment by thelittlebug** [comment]
i've changed the manage.py to get this working.
```
import os
import sys


def main():
    """Run administrative tasks."""
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "highlander.settings.dev")
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)


def prettier_errors():
    import pretty_errors

    pretty_errors.configure()
    pretty_errors.replace_stderr()


if __name__ == "__main__":
    prettier_errors()
    main()

```

**Comment by tankorsmash** [comment]
> i've changed the manage.py to get this working.
> ```
> def prettier_errors():
>     import pretty_errors
> 
>     pretty_errors.configure()
>     pretty_errors.replace_stderr()
> ```

This gets it printing but the HTTP print lines are joined together. I'm on Windows Powershell. I'll update this if I figure out a config to tweak. `full_line_newline=True` isn't it though.

**Comment by nexgen** [comment]
> > i've changed the manage.py to get this working.
> > def prettier_errors():
> >     import pretty_errors
> > 
> >     pretty_errors.configure()
> >     pretty_errors.replace_stderr()
> 
> This gets it printing but the HTTP print lines are joined together. I'm on Windows Powershell.
> 
> Instead of messing with `manage.py`, this middleware gets close for requests but still prints out the error after if you don't return a response from the middleware:
> 
> from sys import exc_info
> import pretty_errors
> 
> class PrettyErrorsMiddleware:
> 	def __init__(self, get_response):
> 		self.get_response = get_response
> 		pretty_errors.configure()
> 
> 	def __call__(self, request):
> 		return self.get_response(request)
> 
> 	def process_exception(self, _, exception):
> 		_, _, traceback = exc_info()
> 		pretty_errors.excepthook(exception.__class__, exception, traceback)
>                 #return http.Response() to stop the error from printing out
> # settings.py
> MIDDLEWARE += ["my.path.to.PrettyErrorsMiddleware"]
> It would be nice to have prettier printing for server startup exceptions, instead of just requests though.

It's not working for me :(
