### ISSUE TITLE
PrettyErrors doesn't work with Hydra

### ISSUE THREAD

**Issue by hobogalaxy** [onelivesleft/PrettyErrors#35]
[Hydra](https://github.com/facebookresearch/hydra/) is framework for ellegantly configuring complex applications.
It seems like PrettyErrors simply doesn't do anything when Hydra is used.
```python
import hydra

@hydra.main(config_path="", config_name="config.yaml")
def main(config):
    raise Exception("Some exception")
    
if __name__ == "__main__":
    main()
```
(if we just comment out the hydra.main decorator then stack trace is printed correctly)

I made and issue about it on Hydra repository: https://github.com/facebookresearch/hydra/issues/1431
It might have to do something with Hydra changing the working directory by default.

Is there any way to make PrettyErrors compatible with Hydra?

**Comment by onelivesleft** [comment]
Closed as per linked issue
