### ISSUE TITLE
Error using global install script with venv

### ISSUE THREAD

**Issue by dkornacki-cutco** [onelivesleft/PrettyErrors#38]
Attempting the global install via python -m pretty_errors under a virtual environment with path C:\venvs\flask results in this trace:

> runpy.py 193 _run_module_as_main
> "__main__", mod_spec)
> 
> runpy.py 85 _run_code
> exec(code, run_globals)
> 
> __main__.py 133 <module>
> found = find_install(True)
> 
> __main__.py 66 find_install
> for path in getallsitepackages():
> 
> __main__.py 54 getallsitepackages
> return getsitepackages() + getusersitepackages()
> 
> __main__.py 42 getsitepackages
> pattern = re.compile(r'^%s$' % os.path.join(os.environ['VIRTUAL_ENV'], 'lib', 'python[0-9.]+', 'site-packages'))re.py 233 compile
> return _compile(pattern, flags)
> 
> re.py 301 _compile
> p = sre_compile.compile(pattern, flags)
> 
> sre_compile.py 562 compile
> p = sre_parse.parse(p, flags)
> 
> sre_parse.py 855 parse
> p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
> 
> sre_parse.py 416 _parse_sub
> not nested and not items))
> 
> sre_parse.py 502 _parse
> code = _escape(source, this, state)
> 
> sre_parse.py 401 _escape
> raise source.error("bad escape %s" % escape, len(escape))
> 
> sre_constants.error:
> bad escape \l at position 15

I attempted to fix by using the method described in another issue, changing regex pattern to allow backslashes in path. But then there is no option to install anywhere:

> (flask) C:\Users\dkornacki\rtc-workspace\iSeries Python\iSeries Python\square_po_import>python -m pretty_errors
> 
> To have pretty_errors be used when you run any python file you may add it to your usercustomize.py (user level) 
> or sitecustomize.py (system level), or to pretty_errors.pth.
> 
> (just hit <enter> to accept the defaults if you are unsure)
> 
> 
>  Choose folder to install into:
> 
> 0: Exit
> 
> Option: [default: 0]

**Comment by onelivesleft** [comment]
Try changing line 42 from: 
`pattern = re.compile(r'^%s$' % os.path.join(os.environ['VIRTUAL_ENV'], 'lib', 'python[0-9.]+', 'site-packages'))`
to
```
pattern_string = r'^%s$' % os.path.join(os.environ['VIRTUAL_ENV'], 'lib', 'python[0-9.]+', 'site-packages')
print(pattern_string)
pattern = re.compile(pattern_string)
```
and post back with what `pattern_string` is. I have an idea of how to fix it but I'd like to make sure before I change anything.

**Comment by dkornacki-cutco** [comment]
^C:\venvs\flask\lib\python[0-9.]+\site-packages$

This is where site-packages actually resides: C:\venvs\flask\Lib\site-packages

**Comment by dkornacki-cutco** [comment]
This fixed it for my setup. I'm guessing this would also work with paths it was working with before:
```python
        def getsitepackages():
            pattern1 = re.compile(r'^%s$' % re.escape(os.path.join(os.environ['VIRTUAL_ENV'], 'lib', 'python[0-9.]+', 'site-packages')))
            pattern2 = re.compile(r'^%s$' % re.escape(os.path.join(os.environ['VIRTUAL_ENV'], 'lib', 'site-packages')))
            paths = [path for path in set(sys.path) if pattern1.search(path) or pattern2.search(path)]
            return paths
```

**Comment by LeonardoSirino** [comment]
> This fixed it for my setup. I'm guessing this would also work with paths it was working with before:
> 
> ```python
>         def getsitepackages():
>             pattern1 = re.compile(r'^%s$' % re.escape(os.path.join(os.environ['VIRTUAL_ENV'], 'lib', 'python[0-9.]+', 'site-packages')))
>             pattern2 = re.compile(r'^%s$' % re.escape(os.path.join(os.environ['VIRTUAL_ENV'], 'lib', 'site-packages')))
>             paths = [path for path in set(sys.path) if pattern1.search(path) or pattern2.search(path)]
>             return paths
> ```

I'm using pipenv on windows and this also worked for me!

**Comment by onelivesleft** [comment]
I've patched in your fix: if you can you test it I'll close this issue

**Comment by dkornacki-cutco** [comment]
Yes, it's working in  v1.2.21. Cleaned startup file and reinstalled.

**Comment by onelivesleft** [comment]
Excellent, thank you!
