### ISSUE TITLE
Use *.pth file instead of sitecustomize.py

### ISSUE THREAD

**Issue by ksamuel** [onelivesleft/PrettyErrors#4]
The `site-packages/sitecustomize.py` file is not reliable loaded for everybody. To ensure pretty_errors is loaded after `python -m pretty_errors`, create a `site-packages/pretty_errors.pth` file containing:

```
import pretty_errors; pretty_errors.configure() # if you add option here, keep it on one line
```

If you don't want to use a *.pth, at least use `/home/user/.local/lib/python3.7/site-packages/usercustomize.py`, which is more likely to be imported and is meant for things like this. But *customize.py files are not imported in venv, which makes them pretty useless for real life Python usage.

**Comment by onelivesleft** [comment]
Can you link me to a simple venv setup I can use for testing?

**Comment by ksamuel** [comment]
You want me to upload a venv in github with a pth to show you how it works ?

**Comment by onelivesleft** [comment]
No, on second thought I almost have .pth working: when I upload it you can see if it meets your needs, and if it doesn't I'll look at setting up a venv.

**Comment by onelivesleft** [comment]
I've updated to 1.2.2, which allows you to use .pth files.  I'm hoping that when it scans available install sites it finds the paths for venv.  Check it out and let me know.

**Comment by ksamuel** [comment]
With 3.7 you'll get: 

```
AttributeError:
module 'site' has no attribute 'getsitepackages'
```

`getsitepackages()` is not always available. Loop over `sys.path` and find the first entry containing 'site-packages'', it's probably your best bet.

**Comment by onelivesleft** [comment]
I'm on 3.7 and it works ok, as it does in 2.7, so there's something else up with that, though I can't guess what it could be.  Looking at the source - https://github.com/python/cpython/blob/2.7/Lib/site.py - it's in all the branches listed, from 3.5 up.

**Comment by ksamuel** [comment]
Either it's not in the virtualenv, or it's not in Python on some OS. Linux maintainers have the bad habits of changing such details.

**Comment by onelivesleft** [comment]
It's probably this: https://github.com/pypa/pipenv/issues/3824

**Comment by ksamuel** [comment]
Something similar yes, as I'm not using pipenv but the bug seems exactly the same.
