### ISSUE TITLE
Jupyter & Vscode

### ISSUE THREAD

**Issue by thoughtfuldata** [onelivesleft/PrettyErrors#42]
I cant seem to get this to work with Jupyter and Vscode. is there something special I need to do?

**Comment by onelivesleft** [comment]
This doesn't seem doable: ipykernel seems to lock down `sys.excepthook` so pretty-errors can't replace it.  Demonstration:

```python
import sys
print(sys.__excepthook__) # original excepthook
print(sys.excepthook)     # current excepthook

import pretty_errors
print(sys.excepthook)

pretty_errors.activate() #just to make sure
print(sys.excepthook)

sys.excepthook = None
print(sys.excepthook)
```

It does the same thing kind of with `stderr`, so `pretty_errors.replace_stderr()` doesn't work either.  I've never used Jupyter though, so am no expert: maybe asking around in Jupyter places about replacing `sys.excepthook` will get you somewhere.
