### ISSUE TITLE
Links in powershell/PyCharm

### ISSUE THREAD

**Issue by thibaut-st** [onelivesleft/PrettyErrors#46]
Hi, 

When I had `display_link=True`, I see the link in the console, but I can't click it inside Pycharm. 
I'm on powershell, no idea if it work on another shell.

Without pretty errors, clickable: 
![clickable](https://user-images.githubusercontent.com/6339836/143566600-90e2dd1c-4285-4b2b-a327-2c6ed64e09a4.JPG)

With pretty errors, not clickable: 
![not-clickable](https://user-images.githubusercontent.com/6339836/143566605-3aef3a8d-0e5f-4b67-8077-a0e8181671c3.JPG)
 

Also, not related, is it planned to have an environment variable for all config parameters? It would be usefull for a general pretty errors install on the system and not having to import pretty errors in the code.

**Comment by onelivesleft** [comment]
You can control the output of the link by making your own `ExceptionWriter` class with a `write_link` method.  See the bottom of the README.  I'd guess that pycharm is looking for `File "...`
