### ISSUE TITLE
Not clickable output

### ISSUE THREAD

**Issue by enajx** [onelivesleft/PrettyErrors#48]
In VSCode default python errors can be clicked and bring the editor will jump to the error line. This doesn't work with pretty errors. 
Could this feature be implemented?

**Comment by onelivesleft** [comment]
See the `display_link` config option.

**Comment by enajx** [comment]
How can it be set when using the system wide install `python -m pretty_errors`? I can set `display_link` if I import pretty_errors within the script but is there a system wide configuration file where it `display_link` can set to true?
