### ISSUE TITLE
[Question] Can I change PrettyErrors' configuration globally?

### ISSUE THREAD

**Issue by Fontanapink** [onelivesleft/PrettyErrors#51]
Or do I have to add
`pretty_errors.configure(
    separator_character = '*',
    filename_display    = pretty_errors.FILENAME_EXTENDED,
    line_number_first   = True,
    display_link        = True,
    lines_before        = 5,
    lines_after         = 2,
    line_color          = pretty_errors.RED + '> ' + pretty_errors.default_config.line_color,
    code_color          = '  ' + pretty_errors.default_config.line_color,
    truncate_code       = True,
    display_locals      = True
)`
at the beginning of each file.

**Comment by onelivesleft** [comment]
Yes, make it run whenever you run python by following the instructions at the top of the readme.  When you do that it will tell you the filename of the startup file it has modified to launch from.  In that file you'll find a commented-out call to `pretty_errors.configure`.

**Comment by Fontanapink** [comment]
The problem is, I've installed it a long time ago. I can find where the module is but looking at __init__.py or __main__.py I can't see where that commented line you are talking about

**Comment by onelivesleft** [comment]
Run "python -m pretty_errors" again
